aider: Imported the `github.com/google/go-querystring/query` package in `client.go` to resolve the undefined `query` error.
# Aider chat conversation:

USER: I ran this command:

 go build .

And got this output:

# kunja/api
api/client.go:259:20: undefined: query

ASSISTANT: The error message indicates that the `query` package is not imported in your `client.go` file. The `query` package is part of the `github.com/google/go-querystring/query` library, which provides functions to encode structs into URL query parameters.

To resolve this issue, you need to import the `github.com/google/go-querystring/query` package in your `client.go` file.

Here is the proposed change:

```go
api/client.go
<<<<<<< HEAD
import (
	"fmt"
	"bytes"
	"encoding/json"
	"errors"
	"io/ioutil"
	"net/http"
)
=======
import (
	"fmt"
	"bytes"
	"encoding/json"
	"errors"
	"io/ioutil"
	"net/http"

	"github.com/google/go-querystring/query"
)
>>>>>>> updated
```

Please note that you need to have the `github.com/google/go-querystring/query` package in your Go module. If it's not already there, you can add it by running `go get github.com/google/go-querystring/query` in your terminal.