aider: Removed unused import "gopkg.in/yaml.v2", added missing import "encoding/json", and commented out reference to undefined "editCmd" in cmd/task.go.
# Aider chat conversation:

USER: I ran this command:

 go build .

And got this output:

# kunja/cmd
cmd/task.go:11:2: "gopkg.in/yaml.v2" imported as yaml and not used
cmd/task.go:85:20: undefined: json
cmd/task.go:141:21: undefined: editCmd

ASSISTANT: To resolve the issues mentioned in the output, we need to make the following changes:

1. Remove the unused import `"gopkg.in/yaml.v2"` from `cmd/task.go`.
2. Add the missing import `"encoding/json"` to `cmd/task.go`.
3. Define or remove the reference to `editCmd` in `cmd/task.go`.

Here are the *SEARCH/REPLACE* blocks for the changes:

cmd/task.go
```go
<<<<<<< SEARCH
import (
	"fmt"
	"kunja/api"
	"strconv"
	"strings"
	"time"

	"github.com/spf13/cobra"
	"gopkg.in/yaml.v2"
)
=======
import (
	"encoding/json"
	"fmt"
	"kunja/api"
	"strconv"
	"strings"
	"time"

	"github.com/spf13/cobra"
)
>>>>>>> REPLACE
```

cmd/task.go
```go
<<<<<<< SEARCH
	rootCmd.AddCommand(doneCmd)
	rootCmd.AddCommand(editCmd)
	rootCmd.AddCommand(assignedCmd)
	rootCmd.AddCommand(usersCmd)
=======
	rootCmd.AddCommand(doneCmd)
	// rootCmd.AddCommand(editCmd) // This line should be removed or uncommented if editCmd is defined elsewhere
	rootCmd.AddCommand(assignedCmd)
	rootCmd.AddCommand(usersCmd)
>>>>>>> REPLACE
```

Please apply these changes to the `cmd/task.go` file. If `editCmd` is defined elsewhere and should be included, please provide the definition for it. Otherwise, the reference to `editCmd` will be commented out as shown above.